# Generated by Django 5.0 on 2024-01-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='page',
            name='precio',
            field=models.FloatField(max_length=7, null=True),
        ),
    ]
