# Generated by Django 5.0 on 2024-01-26 16:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_codigo_descuento_rent_tipo_vehiculo_delete_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='content',
            field=ckeditor.fields.RichTextField(default='Default Content', verbose_name='Contenido'),
            preserve_default=False,
        ),
    ]
