# Generated by Django 5.0 on 2024-01-26 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_id'),
        ('vehiculo', '0003_rent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='codigo_descuento',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tipo_vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page'),
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['order', 'fecha_renta'], 'verbose_name': 'Formulario de renta', 'verbose_name_plural': 'Formularios de renta'},
        ),
        migrations.DeleteModel(
            name='codigo_descuento',
        ),
        migrations.DeleteModel(
            name='tipo_vehiculo',
        ),
    ]
