# Generated by Django 5.0 on 2024-01-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_rent_codigo_descuento_alter_rent_tipo_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='fecha_devolucion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='fecha_renta',
            field=models.DateField(),
        ),
    ]
